### ISSUE TITLE
[3.2] SEO preview no longer works

### ISSUE THREAD

**Issue by Mosnar** [vaersaagod/seomate#16]
It looks like there might have been a breaking change in the last commits before 3.2 was released; as the SEO Preview has stopped working since RC3. 

No console errors. Running SEOmate 1.0.7

**Comment by mmikkel** [comment]
Thanks for reporting, @Mosnar – you're correct; [this commit](https://github.com/craftcms/cms/commit/768572eceb74ec3c1aafdc32da2f23ffb14f450e) is the culprit. That's what you get for hacking the Craft's CP JS layer 🤕 

FWIW, SEO Previews still work for Categories and Commerce Products, as they continue to use the old LivePreview stuff. The new setup for Entries unfortunately looks a bit harder to tap into for our purposes, but hopefully we'll have a fix out relatively soon.

**Comment by mmikkel** [comment]
Quick update: We're hoping to bring back the SEO preview for Entries soon, but seeing as everything related to the new Preview functionality has already seen several core changes since the 3.2.0 release, I'm going to let things simmer a bit longer before digging in.

**Comment by mmikkel** [comment]
We've decided to add the SEO Preview as a Preview Target for Craft 3.2 installs, in [SEOMate v1.1.0](https://github.com/vaersaagod/seomate/releases/tag/v1.1.0). This means that the old "SEO Preview" button is gone for Entries (Categories and Commerce Products still use the legacy Live Preview functionality and will work like before), with a new "SEO Preview" toggle found inside the dropdown in Preview mode. As a side effect, SEO previews are also shareable now (I doubt this is very useful to many people, but it's impossible to add a Preview Target that isn't also added to the "Share" dropdown inside the Entry edit view).

It's kind of a bummer that using Preview Target actually hides the SEO Preview feature away – and the fact that Preview Targets is a Pro only feature is also a bit of a drag (especially since SEOMate is a free plugin). However, as the alternative is adding even more JS Control Panel hacks, I feel that taking advantage of native features is probably the better option in the long run.
