### ISSUE TITLE
sitemap not found - Template not found: sitemap.xml

### ISSUE THREAD

**Issue by bleepsandblops** [vaersaagod/seomate#30]
Hi there,

The route for the sitemap.xml is telling me template not found... this is my config:
```
<?php
return [
    'defaultProfile' => 'standard',
    'fieldProfiles' => [
        'standard' => [
            'title' => ['seoTitle', 'title'],
            'description' => ['seoDescription', 'summary', 'excerpt'],
            'image' => ['headerImage']
        ],
				'insights' => [
            'title' => ['seoTitle', 'title'],
            'description' => ['excerpt'],
            'image' => ['headerImage']					
				]
    ],
    'profileMap' => [
        'insights' => 'insights',
    ],    		
    'sitemapEnabled' => true,
    'sitemapLimit' => 100,
    'sitemapConfig' => [
        'elements' => [
            'book' => ['changefreq' => 'weekly', 'priority' => 1],
            'cafe' => ['changefreq' => 'weekly', 'priority' => 0.5],
            'instructors' => ['changefreq' => 'weekly', 'priority' => 0.5],
        ],
    ],      
];
```
I'm running on latest versions of Craft and Seomate

**Comment by aelvan** [comment]
Your config looks correct, so I suspect that there either is another plugin that registers a route for `sitemap.xml`, or that it is not being processed by craft because it is excluded in your webserver configuration (ie that there's an exclude or a location block for `sitemap.xml`, or maybe all xml-files, in your apache or nginx configuration). 

You could try to change the `sitemapName` config setting to something else to test, if you set it to `'lorem'`, the sitemap-route will be `lorem.xml`.

**Comment by bleepsandblops** [comment]
Thank you @aelvan that's helpful, this fixed itself in the end. I have a strong suspicion I had a wrong config issue on my local server and was looking at the wrong URL... Apologies for not closing the issue.
